Update cicd_pipeline.yml

diff --git a/.github/workflows/cicd_pipeline.yml b/.github/workflows/cicd_pipeline.yml
--- a/.github/workflows/cicd_pipeline.yml
+++ b/.github/workflows/cicd_pipeline.yml
@@ -71,10 +71,10 @@ jobs:
       # -------------------------------------------------------------
       - name: Run smoke test
         run: |
-          if [ ! -f smoketest/smoke_test.py ]; then
-            echo "ERROR: smoketest/smoke_test.py not found."
-            exit 1
-          fi
+          # if [ ! -f smoketest/smoke_test.py ]; then
+          #   echo "ERROR: smoketest/smoke_test.py not found."
+          #   exit 1
+          # fi
           databricks bundle run smoke-test --target dev
         env:
           DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
